image: Visual Studio 2017

install:
 - ls
 - paket.bat restore

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# build Configuration, i.e. Debug, Release, etc.
configuration: Release


after_build:
 - cd
 - set
 - echo $configuration
 - ls MonoSuave/bin

artifacts:
 - path: MonoSuave/bin/$(configuration)

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.zip/           # upload zip file
    draft: false
    prerelease: true
    auth_token:
      secure: MXWyxCowyu8qHT2YssKyplS9byArM3dNycCEq8t6HJPcWY75sOahFIOIwOE7FIQd
    on:
      branch: master                # release from master branch only