image: Visual Studio 2017

install:
 - ls
 - paket.bat restore

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


after_build:
 - ls

artifacts:
 -path: bin