image: Visual Studio 2017

install:
 - ls
 - paket.bat restore

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


after_build:
 - cd
 - ls MonoSuave/MonoSuave

artifacts:
 - path: MonoSuave/MonoSuave/bin/$configuration/